//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppWCF.ServicePachacamac {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsCategoria", Namespace="http://schemas.datacontract.org/2004/07/ClasesBases")]
    [System.SerializableAttribute()]
    public partial class clsCategoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchivoImagen {
            get {
                return this.ArchivoImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoImagenField, value) != true)) {
                    this.ArchivoImagenField = value;
                    this.RaisePropertyChanged("ArchivoImagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrip {
            get {
                return this.DescripField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripField, value) != true)) {
                    this.DescripField = value;
                    this.RaisePropertyChanged("Descrip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePachacamac.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCategorias", ReplyAction="http://tempuri.org/IService1/getCategoriasResponse")]
        WindowsFormsAppWCF.ServicePachacamac.clsCategoria[] getCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCategorias", ReplyAction="http://tempuri.org/IService1/getCategoriasResponse")]
        System.Threading.Tasks.Task<WindowsFormsAppWCF.ServicePachacamac.clsCategoria[]> getCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertCategorias", ReplyAction="http://tempuri.org/IService1/insertCategoriasResponse")]
        void insertCategorias(WindowsFormsAppWCF.ServicePachacamac.clsCategoria xCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertCategorias", ReplyAction="http://tempuri.org/IService1/insertCategoriasResponse")]
        System.Threading.Tasks.Task insertCategoriasAsync(WindowsFormsAppWCF.ServicePachacamac.clsCategoria xCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateCategorias", ReplyAction="http://tempuri.org/IService1/updateCategoriasResponse")]
        void updateCategorias(WindowsFormsAppWCF.ServicePachacamac.clsCategoria xCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateCategorias", ReplyAction="http://tempuri.org/IService1/updateCategoriasResponse")]
        System.Threading.Tasks.Task updateCategoriasAsync(WindowsFormsAppWCF.ServicePachacamac.clsCategoria xCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteCategorias", ReplyAction="http://tempuri.org/IService1/deleteCategoriasResponse")]
        void deleteCategorias(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteCategorias", ReplyAction="http://tempuri.org/IService1/deleteCategoriasResponse")]
        System.Threading.Tasks.Task deleteCategoriasAsync(int idCategoria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsAppWCF.ServicePachacamac.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsAppWCF.ServicePachacamac.IService1>, WindowsFormsAppWCF.ServicePachacamac.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsAppWCF.ServicePachacamac.clsCategoria[] getCategorias() {
            return base.Channel.getCategorias();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppWCF.ServicePachacamac.clsCategoria[]> getCategoriasAsync() {
            return base.Channel.getCategoriasAsync();
        }
        
        public void insertCategorias(WindowsFormsAppWCF.ServicePachacamac.clsCategoria xCategoria) {
            base.Channel.insertCategorias(xCategoria);
        }
        
        public System.Threading.Tasks.Task insertCategoriasAsync(WindowsFormsAppWCF.ServicePachacamac.clsCategoria xCategoria) {
            return base.Channel.insertCategoriasAsync(xCategoria);
        }
        
        public void updateCategorias(WindowsFormsAppWCF.ServicePachacamac.clsCategoria xCategoria) {
            base.Channel.updateCategorias(xCategoria);
        }
        
        public System.Threading.Tasks.Task updateCategoriasAsync(WindowsFormsAppWCF.ServicePachacamac.clsCategoria xCategoria) {
            return base.Channel.updateCategoriasAsync(xCategoria);
        }
        
        public void deleteCategorias(int idCategoria) {
            base.Channel.deleteCategorias(idCategoria);
        }
        
        public System.Threading.Tasks.Task deleteCategoriasAsync(int idCategoria) {
            return base.Channel.deleteCategoriasAsync(idCategoria);
        }
    }
}
